"""empty message

Revision ID: 652281903814
Revises: 8179859958c8
Create Date: 2018-09-05 14:18:53.024799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '652281903814'
down_revision = '8179859958c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['users.id'], )
    )
    op.drop_column('products', 'like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('like', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('registrations')
    # ### end Alembic commands ###
