"""empty message

Revision ID: 8179859958c8
Revises: 846dbf529f01
Create Date: 2018-09-05 12:01:10.945743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8179859958c8'
down_revision = '846dbf529f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('klass', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_klass'), 'products', ['klass'], unique=False)
    op.drop_table('registrations')
    op.drop_index('ix_restaurants_like', table_name='restaurants')
    op.drop_index('restaurant_id', table_name='restaurants')
    op.drop_table('restaurants')
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=True)
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_column('users', 'name')
    op.create_table('restaurants',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('restaurant_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('typecode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('like', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('location', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('restaurant_id', 'restaurants', ['restaurant_id'], unique=True)
    op.create_index('ix_restaurants_like', 'restaurants', ['like'], unique=False)
    op.create_table('registrations',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('restaurant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='registrations_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='registrations_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_products_klass'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
